=== dusanbrkic/vax-is/code/vax/src/main/resources/xsd/digitalni_sertifikat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:dcer="http://www.xml.proj/gradj/digitalni_sertifikat"
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.xml.proj/gradj/digitalni_sertifikat">

    <xs:element name="Digitalni_sertifikat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Osnovni_podaci">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element default="1" name="Broj_sertifikata"
                                type="xs:positiveInteger"/>
                            <xs:element name="Datum_i_vreme_izdavanja" type="xs:dateTime"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Podaci_o_gradjaninu">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ime_i_prezime">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Muski"/>
                                        <xs:enumeration value="Zenski"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Datum_rodjenja" type="xs:date"/>
                            <xs:element name="JMBG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="13"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_pasosa"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="2" minOccurs="1" name="Vakcinacija" type="dcer:TVakcinacija"> </xs:element>
                <xs:element ref="dcer:Sluzbenik"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TVakcinacija">
        <xs:sequence>
            <xs:element name="Tip">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="Pfizer-BioNTech"/>
                        <xs:enumeration value="Sputnik V"/>
                        <xs:enumeration value="Sinopharm"/>
                        <xs:enumeration value="AstraZeneca"/>
                        <xs:enumeration value="Moderna"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Proizvodjac_i_serija">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\w+,\d+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Datum" type="xs:date"/>
            <xs:element name="Zdravstvena_ustanova" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="doza">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="Prva Doza"/>
                    <xs:enumeration value="Druga Doza"/>
                    <xs:enumeration value="TreÄ‡a Doza"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    <xs:element name="Sluzbenik">
        <xs:complexType>
            <xs:all>
                <xs:element name="Ime_i_prezime" type="xs:string"/>
                <xs:element name="Identifikacioni_broj">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="10"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dusanbrkic/vax-is/xml_primeri/digitalni_sertifikat_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<Digitalni_sertifikat xmlns="http://www.xml.proj/gradj/digitalni_sertifikat"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xml.proj/gradj/digitalni_sertifikat ../digitalni_sertifikat.xsd">
    <Osnovni_podaci>
        <Broj_sertifikata>1234</Broj_sertifikata>
        <Datum_i_vreme_izdavanja>2021-11-29T12:00:00</Datum_i_vreme_izdavanja>
    </Osnovni_podaci>
    <Podaci_o_gradjaninu>
        <Ime_i_prezime>Imenko PrezimeniÄ‡</Ime_i_prezime>
        <Pol>Muski</Pol>
        <Datum_rodjenja>1980-01-01</Datum_rodjenja>
        <JMBG>0101980660066</JMBG>
        <Broj_pasosa>0101</Broj_pasosa>
    </Podaci_o_gradjaninu>
    <Vakcinacija>
        <Doza>1/2</Doza>
        <Tip>Pfizer-BioNTech</Tip>
        <Proizvodjac_i_serija>Pfizer,23</Proizvodjac_i_serija>
        <Datum>2021-06-29</Datum>
        <Zdravstvena_ustanova>Dom Zdravlja Novi Sad</Zdravstvena_ustanova>
    </Vakcinacija>
</Digitalni_sertifikat>
