=== dusanbrkic/vax-is/code/vax/src/main/resources/xsd/izvestaj.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:izv="http://www.xml.proj/sluzb/izvestaj"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="http://www.xml.proj/sluzb/izvestaj" elementFormDefault="qualified"
    vc:minVersion="1.1">

    <xs:element name="Izvestaj">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Datum_od" type="xs:date"/>
                <xs:element name="Datum_do" type="xs:date"/>
                <xs:element name="Broj_interesovanja">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:positiveInteger">
                                <xs:attribute name="Tekstualni_naziv" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Broj_zahteva">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:positiveInteger">
                                <xs:attribute name="Tekstualni_naziv" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Broj_izdatih" type="xs:positiveInteger"/>
                <xs:element name="Broj_vakcina">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:positiveInteger">
                                <xs:attribute name="Tekstualni_naziv" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Broj_novovakcinisanih">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:positiveInteger">
                                <xs:attribute name="Tekstualni_naziv" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Brojevi_konkretnih_vakcina">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="Pfizer">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:positiveInteger">
                                            <xs:attribute name="Tekstualni_naziv" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Sinopharm">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:positiveInteger">
                                            <xs:attribute name="Tekstualni_naziv" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Sputnik_V">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:positiveInteger">
                                            <xs:attribute name="Tekstualni_naziv" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="AstraZeneca">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:positiveInteger">
                                            <xs:attribute name="Tekstualni_naziv" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Datum_izdavanja" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dusanbrkic/vax-is/xml_primeri/izvestaj_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<Izvestaj xmlns="http://www.xml.proj/sluzb/izvestaj"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xml.proj/sluzb/izvestaj ../izvestaj.xsd">
    <Datum_od>2021-08-01</Datum_od>
    <Datum_do>2021-09-01</Datum_do>
    <Broj_interesovanja>2758</Broj_interesovanja>
    <Broj_zahteva>453</Broj_zahteva>
    <Broj_izdatih>428</Broj_izdatih>
    <Broj_vakcina>3225</Broj_vakcina>
    <Broj_novovakcinisanih>1789</Broj_novovakcinisanih>
    <Brojevi_konkretnih_vakcina>
        <Pfizer>1625</Pfizer>
        <Sinopharm>1100</Sinopharm>
        <Sputnik_V>356</Sputnik_V>
        <AstraZeneca>144</AstraZeneca>
    </Brojevi_konkretnih_vakcina>
    <Datum_izdavanja>2022-09-11</Datum_izdavanja>
</Izvestaj>
