=== dusanbrkic/vax-is/code/vax/src/main/resources/xsd/zahtev.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1" xmlns:zah="http://www.xml.proj/gradj/zahtev"
    targetNamespace="http://www.xml.proj/gradj/zahtev">

    <xs:element name="Zahtev">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Podnosilac_zahteva">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ime_i_prezime" type="xs:string"/>
                            <xs:element name="Datum_rodjenja" type="xs:date"/>
                            <xs:element name="Pol">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Muski"/>
                                        <xs:enumeration value="Zenski"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="JMBG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="13"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Broj_pasosa"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Razlog_za_podnosenje_zahteva">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="100"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Mesto" type="xs:string"/>
                <xs:element name="Datum" type="xs:date"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dusanbrkic/vax-is/code/vax/src/main/resources/xml/zahtev_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<Zahtev xmlns="http://www.xml.proj/gradj/zahtev"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xml.proj/gradj/zahtev ../zahtev.xsd">
    <Podnosilac_zahteva>
        <Ime_i_prezime>Imenko PrezimeniÄ‡</Ime_i_prezime>
        <Datum_rodjenja>1980-01-01</Datum_rodjenja>
        <Pol>Muski</Pol>
        <JMBG>0101980660066</JMBG>
        <Broj_pasosa>0101</Broj_pasosa>
    </Podnosilac_zahteva>
    <Razlog_za_podnosenje_zahteva>Neki tekst dsadasdsa</Razlog_za_podnosenje_zahteva>
    <Mesto>Novi Sad</Mesto>
    <Datum>2021-12-01</Datum>
</Zahtev>
