=== dusanbrkic/vax-is/code/sluzbenik/src/main/resources/xsd/potvrda.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:pot="http://www.xml.proj/gradj/potvrda"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    targetNamespace="http://www.xml.proj/gradj/potvrda" elementFormDefault="qualified"
    vc:minVersion="1.1">
    <xs:element name="Potvrda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ime" type="xs:string"/>
                <xs:element name="Prezime" type="xs:string"/>
                <xs:element name="Datum_rodjenja" type="xs:date"/>
                <xs:element name="JMBG">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="3" minOccurs="1" name="Vakcinacija" type="pot:TVakcinacija"/>
                <xs:element name="Zdravstvena_ustanova_koja_vakcinise" type="xs:string"/>
                <xs:element name="Naziv_vakcine">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Pfizer-BioNTech"/>
                            <xs:enumeration value="Sputnik V"/>
                            <xs:enumeration value="Sinopharm"/>
                            <xs:enumeration value="AstraZeneca"/>
                            <xs:enumeration value="Moderna"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Datum">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Zdravstvena_ustanova">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="QR_code"/>
            </xs:sequence>
            <xs:attribute name="about"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TVakcinacija">
        <xs:sequence>
            <xs:element name="Datum_davanja" nillable="false" type="xs:date"/>
            <xs:element name="Serija" nillable="false" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== dusanbrkic/vax-is/code/vax/src/main/resources/xml/potvrda_primer.xml
<?xml version="1.0" encoding="UTF-8"?>
<Potvrda xmlns="http://www.xml.proj/gradj/potvrda"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xml.proj/gradj/potvrda ../potvrda.xsd">
    <Ime>Imenko</Ime>
    <Prezime>PrezimeniÄ‡</Prezime>
    <Datum_rodjenja>1980-01-01</Datum_rodjenja>
    <JMBG>0101980660066</JMBG>
    <Vakcinacija>
        <Datum_davanja>2021-03-01</Datum_davanja>
        <Serija>22</Serija>
    </Vakcinacija>
    <Vakcinacija>
        <Datum_davanja>2021-06-01</Datum_davanja>
        <Serija>542</Serija>
    </Vakcinacija>
    <Zdravstvena_ustanova_koja_vakcinise>Dom zdravlja Novi Sad</Zdravstvena_ustanova_koja_vakcinise>
    <Naziv_vakcine>Pfizer-BioNTech</Naziv_vakcine>
    <Datum>2021-12-01</Datum>
    <Zdravstvena_ustanova>Dom zdravlja Novi Sad</Zdravstvena_ustanova>
    <QR_code>qr-code-3123-321dsads--dasd</QR_code>
</Potvrda>
